# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afb4aeb0a78d9be416f3c10bdcdb8b018ef3a701e6b722feb1ce23dff73ec701d59cbe599cd5d4635dce574261fb4905d2bad33b1b00fdaa241e819515696556

test:
  secret_key_base: 37a19100d6be4a4bdfce1cac5b5e3675ef3bea7fcb4af2da1392a2977a6d9e283203f46494a0dca7e8f529328afe8f4024641b4abc47739f7bfe0c8a0f0fc0c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
